version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - ./.certs:/usr/src/app/.certs
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    # network_mode: 'host'

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - ./.certs:/usr/src/app/.certs
  #   command: sh -c "yarn start"
  #   ports:
  #     - "3333:3333"
  #   stdin_open: true
  
  backend-graphql:
    build:
      context: ./docker/
      dockerfile: Dockerfile_bg
    volumes:
      - ./backend-graphql:/app
      - ./.certs:/app/.certs
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    # command: /bin/sh -c 'bundle install'
    ports:
      - '3333:3001'
    tty: true
    stdin_open: true
    # network_mode: 'host'

  # db:
  #   image: mysql:8.0.33
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: jelly_root
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./db/db:/var/lib/mysql
  #     - ./db/seed:/docker-entrypoint-initdb.d
  #   healthcheck:
  #        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pjelly_root"]
  #        timeout: 20s
  #        retries: 5
