version: '3.9'
services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_f
    image: 'jelly-tube/frontend'
    container_name: 'jelly-tube-frontend'
    volumes:
      - type: bind
        source: ../frontend
        target: /usr/src/app
      - type: bind
        source: ../config/env_front
        target: /usr/src/app/.env
    command: sh -c "yarn install && yarn start"
    ports:
      - '3000:3000'
    stdin_open: true
    restart: always

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_b
    image: 'jelly-tube/backend'
    container_name: 'jelly-tube-backend'
    volumes:
      - type: bind
        source: ../backend
        target: /app
      - type: bind
        source: ../config/env_backend.yml
        target: /app/local_config/local_env.yml
    command: /bin/sh -c "bundle install && rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    ports:
      - '3333:3333'
    tty: true
    stdin_open: true
    restart: always

  minio:
    image: 'minio/minio:RELEASE.2023-10-07T15-07-38Z.fips'
    container_name: 'jelly-tube-minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=jelly_minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: -c '/opt/bin/minio server /export --address :9000 --console-address :9001'
    volumes:
      - type: bind
        source: ../minio
        target: /export
