version: '3.9'
services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_f
    image: 'jelly-tube/frontend'
    container_name: 'jelly-tube-frontend'
    volumes:
      - type: bind
        source: ../frontend
        target: /usr/src/app
    command: sh -c "npm i && npm run build && npm run prod"
    ports:
      - '3000:3000'
    stdin_open: true
    restart: always
    networks:
      frontend:
        ipv4_address: 192.168.100.3

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_b
    image: 'jelly-tube/backend'
    container_name: 'jelly-tube-backend'
    volumes:
      - type: bind
        source: ../backend
        target: /app
    command: /bin/sh -c "bundle install && rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    ports:
      - '3333:3333'
    tty: true
    stdin_open: true
    restart: always
    networks:
      frontend:
        ipv4_address: 192.168.100.2
      backend:
        ipv4_address: 192.168.101.2

  minio:
    image: 'minio/minio:RELEASE.2023-10-07T15-07-38Z.fips'
    container_name: 'jelly-tube-minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=jelly_minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    entrypoint: sh
    command: -c '/opt/bin/minio server /export --address :9000 --console-address :9001'
    volumes:
      - type: bind
        source: /media/jelly/HD-TDA/jelly-tube/minio
        target: /export
    restart: always
    networks:
      backend:
        ipv4_address: 192.168.101.3

  lambda:
    build:
      context: ../
      dockerfile: docker/Dockerfile_l
    image: 'jelly-tube/lambda'
    container_name: 'jelly-tube-lambda'
    ports:
      - '5000:5000'
    command: sh -c 'pip install -r requirements.txt && python3 main.py'
    volumes:
      - type: bind
        source: ../m3u8uploader
        target: /app
    restart: always
    networks:
      backend:
        ipv4_address: 192.168.101.4

networks:
  frontend:
    name: jelly-tube-frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  backend:
    name: jelly-tube-backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24
