version: '3.9'
services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_f
    image: 'jelly-tube/frontend'
    container_name: 'jelly-tube-frontend'
    restart: always
    volumes:
      - ../frontend:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - '3000:3000'
    stdin_open: true

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_b
    image: 'jelly-tube/backend'
    container_name: 'jelly-tube-backend'
    restart: always
    volumes:
      - ../backend:/app
    command: /bin/sh -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3001"
    ports:
      - '3333:3001'
    tty: true
    stdin_open: true

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - frontend
    restart: always
    environment:
      DOMAINS: 'jelly-fish.local -> http://frontend:3000, api.jelly-fish.local -> http://backend:3001'
      STAGE: 'local'
    volumes:
      - ../https-portal:/var/lib/https-portal
