version: '3.9'
services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_f
    image: 'jelly-tube/frontend'
    container_name: 'jelly-tube-frontend'
    volumes:
      - ../frontend:/usr/src/app
      - ../.certs:/usr/src/app/.certs
    command: sh -c "yarn install && yarn start"
    ports:
      - '3000:3000'
    stdin_open: true
    restart: always

  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile_b
    image: 'jelly-tube/backend'
    container_name: 'jelly-tube-backend'
    volumes:
      - ../backend:/app
      - ../.certs:/app/.certs
    command: /bin/sh -c "bundle install && rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - '3333:3001'
    tty: true
    stdin_open: true
    restart: always

  # db:
  #   image: mysql:8.0.33
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: jelly_root
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./db/db:/var/lib/mysql
  #     - ./db/seed:/docker-entrypoint-initdb.d
  #   healthcheck:
  #        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pjelly_root"]
  #        timeout: 20s
  #        retries: 5
