FROM ruby:3.2.2
# 公式→https://hub.docker.com/_/ruby

# Rails 7ではWebpackerが標準では組み込まれなくなったので、yarnやnodejsのインストールが不要

# ruby3.1のイメージがBundler version 2.3.7で失敗するので、gemのバージョンを追記
ENV BUNDLE_APP_CONFIG=/app/vendor/bundle

RUN mkdir /app
WORKDIR /app

# ローカルのGemfileをコンテナ内の/app/Gemfileに
COPY backend/Gemfile /app/Gemfile
COPY backend/Gemfile.lock /app/Gemfile.lock

# RubyGemsをアップデート
# RUN bundle install

# コンテナ起動時に実行させるスクリプトを追加
COPY backend/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3001

# Rails サーバ起動
CMD ["rails", "server", "-b", "0.0.0.0"]
